### ISSUE TITLE
I can't launch with modensplash

### ISSUE THREAD

**Issue by Hellokhe** [kappa-maintainer/ModernSplash#16]
Prism Launcher version: 9.1 (official)

Launched instance in online mode

login.microsoftonline.com resolves to:
    [40.126.28.23, 40.126.28.19, 20.190.135.7, 20.190.135.5, 40.126.7.35, 40.126.28.12, 40.126.28.14, 40.126.28.22]

session.minecraft.net resolves to:
    [13.107.246.41]

textures.minecraft.net resolves to:
    [13.107.246.41]

api.mojang.com resolves to:
    [13.107.246.41]

Minecraft folder is:
/Users/maxdelgado/Library/Application Support/PrismLauncher/instances/its new-/minecraft

Compatible Java found at: /Users/maxdelgado/Library/Application Support/PrismLauncher/java/jre-legacy/bin/java.
Java path is:
/Users/maxdelgado/Library/Application Support/PrismLauncher/java/jre-legacy/bin/java

Checking Java version...
Java is version 1.8.0_432, using 64 (aarch64) architecture, from Azul Systems, Inc..

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /Users/maxdelgado/Library/Application Support/PrismLauncher/instances/its new-/natives

Libraries:
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/ca/weblite/java-objc-bridge/1.1.0-mmachina.1/java-objc-bridge-1.1.0-mmachina.1.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2859/forge-1.12.2-14.23.5.2859-universal.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx-arm64.jar
  /Users/maxdelgado/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx-arm64.jar

Mods:
  [✔] modernsplash-1.12.2-1.3

Params:
  --username  --version 1.12.2 --gameDir /Users/maxdelgado/Library/Application Support/PrismLauncher/instances/its new-/minecraft --assetsDir /Users/maxdelgado/Library/Application Support/PrismLauncher/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="Prism Launcher: its new?", -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 7891

[14:28:43] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:28:43] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:28:43] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[14:28:43] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2859 for Minecraft 1.12.2 loading
[14:28:43] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_432, running on Mac OS X:aarch64:14.6.1, installed at /Users/maxdelgado/Library/Application Support/PrismLauncher/java/jre-legacy/zulu-8.jre/Contents/Home
[14:28:43] [main/INFO] [FML]: Searching /Users/maxdelgado/Library/Application Support/PrismLauncher/instances/its new-/minecraft/mods for mods
[14:28:43] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from modernsplash-1.12.2-1.3.jar
[14:28:43] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:28:43] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[14:28:43] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_432]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_432]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_432]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_432]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_432]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_432]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_432]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_432]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[14:28:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[14:28:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[14:28:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[14:28:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:102)
[14:28:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:987)
[14:28:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:75)
Exception caught from launcher
net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:102)
	at java.lang.System.exit(System.java:987)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ERROR
Process exited with code 1.

**Comment by kappa-maintainer** [comment]
Mixin not installed
